# Generated by Django 4.2 on 2024-01-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_item_itemorder_items_requestitemorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='items',
            new_name='item',
        ),
    ]
