# Generated by Django 4.2 on 2024-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_category_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
