# Generated by Django 5.1 on 2024-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_apply_tax_iva_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Externo'),
        ),
    ]
