# Generated by Django 4.2 on 2024-01-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=400),
        ),
    ]
