# Generated by Django 4.2 on 2024-01-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('files', '0003_alter_image_options_image_height_image_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='ticket_pdfs/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='orders.order')),
            ],
        ),
    ]
