# Generated by Django 4.2 on 2024-03-18 18:33

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_itemorder_quantity'),
        ('files', '0004_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/category_images/', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='items.category')),
            ],
            options={
                'verbose_name': 'Imagen de Categoria',
                'verbose_name_plural': 'Imagenes de Categoria',
            },
        ),
    ]
